### PR TITLE
feedback

### PR DESCRIPTION
**Pull request by mlewandowski0**
I added few comments/suggestions on the schematic, let me know if you wil want to discuss

### CODE REVIEW

**Comment by mlewandowski0** [comment]
Here is also a .pdf render of comments
[DAWG_ServoDriver.pdf](https://github.com/RawanElsayed00/DAWG_ServoDriver_Board/files/14894393/DAWG_ServoDriver.pdf)

**Comment by RawanElsayed00** [comment]
Yes thanks for the comments I am good with all but one. The Servo Header comment I don't get what you mean?

**Comment by RawanElsayed00** [comment]
- The VDDA Pin it doesn't need a decoupling capacitor
- For the IMU SAO pin I pulled high to use GND for LiDAR
- Why connect NOT sleep to GND? please explain
- For the buck converter 3.3V, how can i connect 3.3V if the power input is from the battery? please explain

**Comment by mlewandowski0** [comment]
- The VDDA Pin it doesn't need a decoupling capacitor : are you 100% sure ? typically they would put a FB from digital VDD and VDDA, but I think they always put some decoupling. I'm fairly sure that most of the hardware design guidelines say place a decoupling capacitor per power pin (please see the screenshot attached)

- For the IMU SAO pin I pulled high to use GND for LiDAR : oh, are we really that unlucky that that IMU share the I2C address with LIDAR ? I didn't check the addresses, when I wrote that comment I thought they are different (did it quickly, didn't check the datasheet) 

- for the SLEEP, it seems that this feedback system look like it isn't necessary, we want that step down to always to work no ? (when powered, we always want the MCU to work), it's also not a configuration from datasheet, I would just make the converter never sleep (always on)

- as far as I aware, we decided to use either 3S Lithium-Ion battery. This gives voltage in range [11.1, 12.6], and we decided we have another, high power converter (different board) that will convert that to desired servo voltage (depends what we will use, it's regulated, but from 6.8 to 8V, or 10-12V for dynamixels ). That would mean that the Vbat on that schematics is ~8V, so step-down converter will convert this to 3.3V for MCU (so output of that stepdown is +3.3V line, and that would have to be reflected on schematic).

-  The Servo Header comment : you can probably ignore it, it's just that the Vbat (or just voltage on the screw terminal) has to be desired voltage on servo (which is not amazing assumption I guess). It's probably fine, as we will have other high efficiency and power step-down (3S to ~8V)

image

**Comment by RawanElsayed00** [comment]
- I know that each pin needs a decoupling capacitor then a bulk capacitor, but in this case VDDA is just attached to VDD so thats why am hesitant, check this please: https://community.st.com/t5/stm32-mcus-products/stm32l412-no-decoupling-caps-for-vdda-if-not-used/td-p/163881
- This one i can fix no need for sharing my bad, I can fit another I2C. Then that means that the SAO should be GND? but i thought it can be pulled to VDDIO or GND, please check the new LiDAR connection below
- Got it. Done.
- So instead of +3.3V it should be 3.3Vout
- This one am working on it

Thanks Maciej!

image

**Comment by mlewandowski0** [comment]
- 1. yeah, it makes sense (checked the datasheet it would seem fine, the peripherals would be off). If I were you however, I would still put the capacitor there (just like a good practice, it doesn't harm anything, and you don't have to remember in future about putting that extra cap, if you will want to add any ADC/DAC peripherals, for some feedback system)
- 2. yeah SAO could be GND (I think it's a bit more intuitive, the LSB of the address is set then to 0, makes more sense then to set to 1, at least to me). With this line of I2C for Lidar, I just checked and the line is 5V. That would mean we need another logic level converter from that line and the I2C line from STM32 
- 4. yeah, or you could replace 3.3Vout with +3.3V

Let me know if anything is unclear

**Comment by RawanElsayed00** [comment]
This is the final comment, should it be like this for the LLC: 

image

If all is good I will send push the schematic again and you can take a final look. 
Thanks Maciej!

**Pull request closed without merging**
